# For more info on HTTP files go to https://aka.ms/vs/httpfile
POST https://localhost:57878/produtos
Content-Type: application/json

{
  "name": "Mouse Optico USB",
  "price": 50.00,
  "estoque": 2
}

###

GET https://localhost:57878/produtos

###

POST https://localhost:57878/vendas
Content-Type: application/json

{
  "produtoId":1,
  "quantidade":1
}

###

GET https://localhost:57878/produtos/estoque-baixo

###

GET https://localhost:57878/produtos/financeiro-critico